### ISSUE TITLE
React Native: Package subpath './package.json' is not defined by "exports"

### ISSUE THREAD

**Issue by brianlenz** [fb55/domutils#1054]
When using domutils v3 in a React Native project, you'll get a warning when building:

```
warn Package domutils has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in $PATH/node_modules/domutils/package.json
```

This is something that has been reported for multiple packages in React Native here:

https://github.com/react-native-community/cli/issues/1168

Each individual package maintainer has the ability to work around the issue, however, by simply exporting package.json. I'll submit a PR to do this and leave it up to you @fb55 if you'd like to merge.

**Comment by fb55** [comment]
Hi @brianlenz, do you know why the `package.json` is loaded in the first place?

**Comment by brianlenz** [comment]
Hi @fb55, honestly, I don't fully understand the background, but from the issue I linked, here's the explanation:

> The reason is that, starting in Node.js 14.x, as soon as an npm module defines the `exports` field in `package.json`, only the files listed there are exported. If `package.json` is not included in that list, it's no longer possible to do things like `require.resolve('uuid/package.json');`.
>
> The problematic piece of code is:
> 
> https://github.com/react-native-community/cli/blob/5819a17d148726a1185420b6df345dad6c81c81b/packages/cli/src/tools/config/resolveNodeModuleDir.ts#L11-L13

And then there is further background provided in a comment here:

https://github.com/react-native-community/cli/issues/1168#issuecomment-628055339

Given that the issue has been open in React Native for years, it seems there isn't a resolution coming on their end anytime soon. Most other projects in this situation have addressed the problem as I addressed it in the PR here (which you can see by all of the links to other projects in the issue).

Since React Native is such a popular framework, I figured it would be best for `domutils` to apply the same workaround to prevent the warning.

**Comment by fb55** [comment]
I will follow Sindre's lead here (https://github.com/react-native-community/cli/issues/1168#issuecomment-1192741058), and won't be adding the `package.json` file to itself. As a workaround, you can use an earlier version of this module that doesn't provide an export map yet (the 2.x releases are fine).

**Comment by brianlenz** [comment]
@fb55, bummer, that's too bad. I guess we are stuck patching your package for the foreseeable future 😩 For anyone else who comes here with the same issue, you can use this patch file to fix it (either with Yarn 2 patch or patch-package):

```
diff --git a/package.json b/package.json
index 7955573aded67b578c6014d5e1bc94056f67f5a1..edc4e30427ff7e01b7869f3ea8b81b74488b1dcb 100644
--- a/package.json
+++ b/package.json
@@ -12,8 +12,11 @@
     "types": "lib/index.d.ts",
     "module": "lib/esm/index.js",
     "exports": {
-        "require": "./lib/index.js",
-        "import": "./lib/esm/index.js"
+        "./package.json": "./package.json",
+        ".": {
+            "require": "./lib/index.js",
+            "import": "./lib/esm/index.js"
+        }
     },
     "files": [
         "lib/**/*"
```

**Comment by fb55** [comment]
Is there a particular feature you need from the 3.x releases? Staying on an older version seems like much simpler solution here — but don't let me stop you from doing what's best for you.

**Comment by brianlenz** [comment]
> Is there a particular feature you need from the 3.x releases? Staying on an older version seems like much simpler solution here — but don't let me stop you from doing what's best for you.

@fb55, I appreciate the consideration and help! 🙏 In our case, it's a transitive dependency that we don't have direct control over. I suppose forcing a downgrade through resolution _may_ work, but it doesn't seem like a particularly good idea.

It may not ultimately matter, as it looks like react-native-cli may actually be addressing the root cause, though! Just now:

https://github.com/react-native-community/cli/pull/1655

Glad to see after 2+ years 😁
