### ISSUE TITLE
Infinite loop when using compareDocumentPosition() with nested nodes

### ISSUE THREAD

**Issue by jwbth** [fb55/domutils#109]
```js
var dom = htmlparser.parseDOM('<div><span>1</span><span>2</span></div>');
htmlparser.DomUtils.compareDocumentPosition(dom[0].children[0], dom[0].children[0].children[0]);
```
This code causes an infinite loop. The debugger shows the execution looping here:
```js
    while (aParents[idx] === bParents[idx]) {
        idx++;
    }
```
With adjecent nodes, it's OK.

Environment: browserified & babelified (`{ targets: '> 1%, not IE 11' }`) module, web worker, Chrome 78.

**Comment by fb55** [comment]
Thanks a lot for the report! Fixed this on master.
