### ISSUE TITLE
Any reason why `appendChild` only allows `Element` and not `NodeWithChildren`?

### ISSUE THREAD

**Issue by vidhu** [fb55/domutils#1188]
Based on the function name, we should be able to append child to anything that can take children, right? 

Due to the current typing
```ts
function appendChild(elem: Element, child: ChildNode): void
```

I get a type error with the following code
```ts
const doc = new Document([]);

const newHtmlElement = new Element('html', {}, undefined, ElementType.Tag);

appendChild(doc, newHtmlElement);
```

The code runs fine however typescript complains since `Document` is not an `Element`;

I think the typing is incorrect and should be 
```ts
function appendChild(elem: NodeWithChildren, child: ChildNode): void
```
but correct me if I'm misunderstanding

**Comment by fb55** [comment]
`NodeWithChildren` makes sense to me
