### ISSUE TITLE
No examples & documentation

### ISSUE THREAD

**Issue by Pajamaman** [fb55/domutils#12]
Some examples or usage info would be nice.

**Comment by fb55** [comment]
Yes, definitely. The main issue though is the lack of focus of this module, which should be fixed by separating the individual components and documenting them separately.

**Comment by revelt** [comment]
It's incredible that nobody took time to contribute documenting this famous library. Everybody seem to use it, yet there's no clue how to use it. I'm wrestling with simple things such as how to even use `DomUtils`...

**Comment by fb55** [comment]
Please feel free to contribute documentation.

**Comment by kennylbj** [comment]
@revelt hahaha, can anyone save me plz

**Comment by fb55** [comment]
Added docs

**Comment by youyinnn** [comment]
Still don't know how to use it

``` js
const root = htmlparser2.parseDocument(data);
console.log(root); 
```

I got my Document, then what ?
How am I suppose to use thei domutils with the Document object?
