### ISSUE TITLE
What's the difference between find and findAll?

### ISSUE THREAD

**Issue by thorn0** [fb55/domutils#39]
Seems like `findAll` does the same thing as `find` called with `recurse=true` and `limit=Infinity`, but it has a separate implementation. Both are deep-first. Am I missing something and are they supposed to do different things?

**Comment by fb55** [comment]
`findAll` is supposed to be a bit faster than `find`.

**Comment by thorn0** [comment]
Also `findAll' finds only tags while `find` can be used to find nodes of any type.
