### ISSUE TITLE
TypeError: ext[key].bind is not a function

### ISSUE THREAD

**Issue by tobsch** [fb55/domutils#520]
Hey,

I have a problem on Digital Ocean App Platform:
```[2021-01-09T09:47:25.184Z] error TypeError: ext[key].bind is not a function
15:17:25     at /workspace/node_modules/css-select/node_modules/domutils/index.js:12:28
```

It is while compiling javascript using gatsby.
Any idea as it seems to come from this package?

Tobias

**Comment by fb55** [comment]
IIRC this was an issue with an older version of this package and should be fixed. If upgrading doesn't solve it, please send a summary of all of the versions you use (Node, css-select, etc.).

**Comment by tobsch** [comment]
@fb55 it still exists in the current stable version? 2.4.4 still has it.

**Comment by tobsch** [comment]
@fb55 should we check if the current preview works?

**Comment by fb55** [comment]
`domutils/index.js:12:28` is not a path of the current version. The `index.js` file is now in the `lib` directory.

**Comment by TravisNP** [comment]
Could someone post a more in-depth fix? I'm having the same issue but I am trying to run Docker using WSL2.
node: 18.9.1
Windows: 21H1 (OS Build 19043.2006)

**Comment by fb55** [comment]
Fix for this is to upgrade to a newer version.

**Comment by TravisNP** [comment]
> Fix for this is to upgrade to a newer version.

Hey! Could you please elaborate? Newer version of what exactly. I am on the newest version of node and Docker.

**Comment by fb55** [comment]
Newer version of this library, `domutils`.

**Comment by TravisNP** [comment]
> Newer version of this library, `domutils`.

When I run npm list, I get the following output

domutils@1.5.1 /mnt/c/Users/morepathhere/Django                                                                                                 
├── dom-serializer@0.2.2                                                                                                                                 
├── domelementtype@1.3.1                                                                                                                                 
├── domhandler@2.4.2                                                                                                                                     
├── domutils@3.0.1                                                                                                                                       
├── htmlparser2@3.3.0                                                                                                                                    
├── jshint@2.13.5                                                                                                                                        
└── mocha@10.0.0

Thank you, I see that domutils is at the latest version below, but I think my project is pulling from the top version of 1.5.1.
