### ISSUE TITLE
Can not install 2.5.2

### ISSUE THREAD

**Issue by lpeter218065** [fb55/domutils#586]
Hello, 

It seems I can not install 2.5.2 version, is this expected?

![image](https://user-images.githubusercontent.com/4799347/114181561-3aff5480-9974-11eb-9eae-0b0eec4a700c.png)

**Comment by fb55** [comment]
There is a chance that npm takes a moment to get the package to all servers. The npm website lists this version.

I am closing this as I assume it is some consistency issue within npm. Happy to reopen should the issue persists for another 24h.

As for a fix, 2.5.1 is essentially the same, and you won't break anything by using that version. (You are missing out on a dom-serializer update, which should be fine.)
