### ISSUE TITLE
Cannot find version 1.5.1

### ISSUE THREAD

**Issue by arakeshrohan** [fb55/domutils#75]
Hey, 
I am trying to look at the source code for 1.5.1 which was used in _htmlparser2_ and _cheerio_ 0.22.0 version. But i cannot find it under the releases. Can you please help me find it?

**Comment by fb55** [comment]
This is the commit with the release: https://github.com/fb55/domutils/commit/7d4bd16cd36ffce62362ef91616806ea27e30d95
