### ISSUE TITLE
Only for Enterprise and how to use with htmlparser2?

### ISSUE THREAD

**Issue by ivanjeremic** [fb55/domutils#824]
Is this package paid only? And from the documentation, it is not clear to me how to use it with htmlparser2 are there any examples that show how to use them together?

**Comment by fb55** [comment]
Hi! The library is not paid only, you can just install it from NPM; it is released under a BSD-2-clause license, so freely available.

The website has a lot more details on which methods are available: https://domutils.js.org

To get a DOM in the first place, htmlparser2 has a `parseDocument` method.

If you want to make your life easier and you are familiar with jQuery, you might want to check out the `cheerio` library, which wraps around both packages.
